spring:
  data:
    mongodb:
      host: localhost #can be internal host if Bong server is under the same host
      port: 27017


server:
  port: 8080

dataLoad:
  updateData: true # like create-drop
  accessKey: MeGciGaBMDSwhOhVPBjKWoECZlF2LPdJ1UPGdXp1qWU
